### ISSUE TITLE
Replace ror-dependencies with Conan

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1548]
See https://conan.io for more info about conan

## TODO

- [ ] Ogre3D
- [ ] ~~MyGUI~~: Will be replaced with IMGUI
- [x] OpenAL: https://bintray.com/bincrafters/public-conan/openal%3Abincrafters
- [x] AngelScript: https://bintray.com/anotherfoxguy/ror-dependencies/AngelScript%3Aanotherfoxguy
- [x] SocketW: https://bintray.com/anotherfoxguy/ror-dependencies/SocketW%3Aanotherfoxguy
- [ ] ~~PagedGeometry~~: See #1483 
- [ ] ~~Caelum~~: Will be removed
- [x] RapidJSON: https://bintray.com/bincrafters/public-conan/rapidjson%3Abincrafters
- [ ] MofileReader
- [x] WxWidgets: https://bintray.com/bincrafters/public-conan/wxwidgets%3Abincrafters

**Comment by tritonas00** [comment]
What's wrong with cmake?

**Comment by only-a-ptr** [comment]
Uhh, I'm feeling old. It seems new technologies emerge faster than I'm able to discover and learn them. 😄 

@tritonas00 Nothing's wrong with CMake, Conan just provides hosting and on-demand deployment of the binaries (if I understand correctly)

@AnotherFoxGuy Dropping MyGUI means to re-implement loading XML .layout files used for our modern dashboards. We can either prioritize this or keep MyGUI for the time being.

**Comment by only-a-ptr** [comment]
@tritonas00 I guess not really, but I didn't research. I'll focus on it.
