### ISSUE TITLE
Upgrade to VS 2019

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#2347]
## Todo

- [x] Upgrade AngelScript conan package to VS 2019
- [x] Upgrade MofileReader conan package to VS 2019
- [x] Upgrade OGREdeps conan package to VS 2019
- [x] Upgrade MyGUI conan package to VS 2019
- [x] Upgrade OGRE conan  package to VS 2019
- [x] Upgrade SocketW conan package to VS 2019
- [x] Upgrade ogre-caelum conan package to VS 2019
- [x] Upgrade AppVeyor build to VS 2019

**Comment by only-a-ptr** [comment]
I wanted to build with VS2019 today, but stable conan doesn't support it yet: https://github.com/conan-io/cmake-conan/pull/144

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr Conan 1.14 supports VS 2019, make sure that you have the latest version install with `pip install conan -U`

**Comment by AnotherFoxGuy** [comment]
@only-a-ptr I've just tried building with VS 2019, it works without any issues

**Comment by only-a-ptr** [comment]
Now there's Conan 1.15 already 😆
